site_name: SurveySavvy
site_description: Student Unit Survey Database Generator
site_author: SurveySavvy Team
repo_url: https://github.com/yourusername/surveysavvy

theme:
  name: material
  palette:
    primary: indigo
    accent: amber
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.emoji
  - def_list
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - User Guide: 
    - Installation: user-guide/installation.md
    - Quick Start: user-guide/quick-start.md
    - Command Line Interface: user-guide/cli.md
    - Python API: user-guide/api.md
  - Technical Reference:
    - Database Schema: technical/schema.md
    - Data Generation: technical/generation.md
    - Comment Generation: technical/comments.md
  - Contributing: contributing.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            heading_level: 2